// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEVSN0a8AU2l3PGZhvVAibXA6Ppp2ngD8',
    appId: '1:365442623958:web:0a5359b842d96a632f9c77',
    messagingSenderId: '365442623958',
    projectId: 'crud-5a0dd',
    authDomain: 'crud-5a0dd.firebaseapp.com',
    storageBucket: 'crud-5a0dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZhNqU7oW_teC8mVvA3J5QmCRub2Qyr9o',
    appId: '1:365442623958:android:e8a7a67fb3cf59862f9c77',
    messagingSenderId: '365442623958',
    projectId: 'crud-5a0dd',
    storageBucket: 'crud-5a0dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_BMvhvFFc9smB-SOvpX-Otm3c5JzUepU',
    appId: '1:365442623958:ios:2c7fa9fc1ca480062f9c77',
    messagingSenderId: '365442623958',
    projectId: 'crud-5a0dd',
    storageBucket: 'crud-5a0dd.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_BMvhvFFc9smB-SOvpX-Otm3c5JzUepU',
    appId: '1:365442623958:ios:2c7fa9fc1ca480062f9c77',
    messagingSenderId: '365442623958',
    projectId: 'crud-5a0dd',
    storageBucket: 'crud-5a0dd.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEVSN0a8AU2l3PGZhvVAibXA6Ppp2ngD8',
    appId: '1:365442623958:web:adac4f9963891ef32f9c77',
    messagingSenderId: '365442623958',
    projectId: 'crud-5a0dd',
    authDomain: 'crud-5a0dd.firebaseapp.com',
    storageBucket: 'crud-5a0dd.appspot.com',
  );
}
